package com.upb.agripos.service;

import com.upb.agripos.model.audit.AuditLog;
import com.upb.agripos.model.audit.AuditAction;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit Test untuk AuditLogServiceImpl
 * Test logging dan filtering audit logs
 * Person A - AUDIT LOG SERVICE TEST
 */
@DisplayName("Audit Log Service Tests")
class AuditLogServiceImplTest {
    
    private AuditLogServiceImpl auditLogService;
    
    @BeforeEach
    void setUp() {
        auditLogService = new AuditLogServiceImpl();
    }
    
    // ========== LOG TESTS ==========
    
    @Test
    @DisplayName("Should log audit event successfully")
    void testLogEventSuccessfully() {
        // Act
        auditLogService.log(
            "LOG-001",
            "USER-001",
            "TRX-001",
            AuditAction.TRANSACTION_START,
            "Transaksi dimulai"
        );
        
        // Assert
        assertEquals(1, auditLogService.getTotalLogs());
    }
    
    @Test
    @DisplayName("Should log event with auto-generated log ID")
    void testLogWithAutoGeneratedId() {
        // Act
        auditLogService.log(
            null,
            "USER-001",
            "TRX-001",
            AuditAction.PAYMENT_SUCCESS,
            "Pembayaran berhasil"
        );
        
        // Assert
        assertEquals(1, auditLogService.getTotalLogs());
    }
    
    @Test
    @DisplayName("Should fail logging with null user ID")
    void testLogNullUserId() {
        // Act & Assert
        assertThrows(IllegalArgumentException.class, () -> {
            auditLogService.log(
                "LOG-002",
                null,
                "TRX-001",
                AuditAction.PAYMENT_SUCCESS,
                "Pembayaran berhasil"
            );
        });
    }
    
    @Test
    @DisplayName("Should fail logging with null action")
    void testLogNullAction() {
        // Act & Assert
        assertThrows(IllegalArgumentException.class, () -> {
            auditLogService.log(
                "LOG-003",
                "USER-001",
                "TRX-001",
                null,
                "Detail"
            );
        });
    }
    
    @Test
    @DisplayName("Should log event with custom IP address")
    void testLogWithIpAddress() {
        // Act
        auditLogService.logWithIp(
            "LOG-004",
            "USER-001",
            "TRX-001",
            AuditAction.TRANSACTION_START,
            "Test log",
            "192.168.1.1"
        );
        
        // Assert
        List<AuditLog> logs = auditLogService.getLogsByUser("USER-001");
        assertEquals(1, logs.size());
        assertEquals("192.168.1.1", logs.get(0).getIpAddress());
    }
    
    // ========== GET LOGS BY TRANSACTION TESTS ==========
    
    @Test
    @DisplayName("Should retrieve logs by transaction ID")
    void testGetLogsByTransaction() {
        // Arrange
        auditLogService.log("LOG-005", "USER-001", "TRX-001", AuditAction.TRANSACTION_START, "Start");
        auditLogService.log("LOG-006", "USER-001", "TRX-001", AuditAction.ITEM_ADDED, "Item");
        auditLogService.log("LOG-007", "USER-002", "TRX-002", AuditAction.TRANSACTION_START, "Start");
        
        // Act
        List<AuditLog> logs = auditLogService.getLogsByTransaction("TRX-001");
        
        // Assert
        assertEquals(2, logs.size());
    }
    
    @Test
    @DisplayName("Should return empty list for non-existent transaction")
    void testGetLogsByNonExistentTransaction() {
        // Act
        List<AuditLog> logs = auditLogService.getLogsByTransaction("TRX-999");
        
        // Assert
        assertEquals(0, logs.size());
    }
    
    @Test
    @DisplayName("Should return empty list for null transaction ID")
    void testGetLogsByNullTransaction() {
        // Act
        List<AuditLog> logs = auditLogService.getLogsByTransaction(null);
        
        // Assert
        assertEquals(0, logs.size());
    }
    
    // ========== GET LOGS BY USER TESTS ==========
    
    @Test
    @DisplayName("Should retrieve logs by user ID")
    void testGetLogsByUser() {
        // Arrange
        auditLogService.log("LOG-008", "USER-001", "TRX-001", AuditAction.TRANSACTION_START, "Start");
        auditLogService.log("LOG-009", "USER-001", "TRX-002", AuditAction.PAYMENT_SUCCESS, "Pay");
        auditLogService.log("LOG-010", "USER-002", "TRX-003", AuditAction.TRANSACTION_START, "Start");
        
        // Act
        List<AuditLog> logs = auditLogService.getLogsByUser("USER-001");
        
        // Assert
        assertEquals(2, logs.size());
    }
    
    @Test
    @DisplayName("Should return empty list for non-existent user")
    void testGetLogsByNonExistentUser() {
        // Act
        List<AuditLog> logs = auditLogService.getLogsByUser("USER-999");
        
        // Assert
        assertEquals(0, logs.size());
    }
    
    // ========== GET LOGS BY ACTION TESTS ==========
    
    @Test
    @DisplayName("Should retrieve logs by action type")
    void testGetLogsByAction() {
        // Arrange
        auditLogService.log("LOG-011", "USER-001", "TRX-001", AuditAction.TRANSACTION_START, "Start");
        auditLogService.log("LOG-012", "USER-002", "TRX-001", AuditAction.TRANSACTION_START, "Start");
        auditLogService.log("LOG-013", "USER-001", "TRX-002", AuditAction.PAYMENT_SUCCESS, "Pay");
        
        // Act
        List<AuditLog> logs = auditLogService.getLogsByAction(AuditAction.TRANSACTION_START);
        
        // Assert
        assertEquals(2, logs.size());
    }
    
    @Test
    @DisplayName("Should return empty list for action with no logs")
    void testGetLogsByUnusedAction() {
        // Arrange
        auditLogService.log("LOG-014", "USER-001", "TRX-001", AuditAction.TRANSACTION_START, "Start");
        
        // Act
        List<AuditLog> logs = auditLogService.getLogsByAction(AuditAction.STOCK_UPDATED);
        
        // Assert
        assertEquals(0, logs.size());
    }
    
    // ========== GET ALL LOGS TESTS ==========
    
    @Test
    @DisplayName("Should retrieve limited number of logs")
    void testGetAllLogsWithLimit() {
        // Arrange
        for (int i = 0; i < 10; i++) {
            auditLogService.log("LOG-" + i, "USER-001", "TRX-001", 
                AuditAction.TRANSACTION_START, "Log " + i);
        }
        
        // Act
        List<AuditLog> logs = auditLogService.getAllLogs(5);
        
        // Assert
        assertEquals(5, logs.size());
    }
    
    @Test
    @DisplayName("Should return all logs when limit exceeds total")
    void testGetAllLogsExceedingLimit() {
        // Arrange
        auditLogService.log("LOG-15", "USER-001", "TRX-001", AuditAction.TRANSACTION_START, "Log");
        auditLogService.log("LOG-16", "USER-001", "TRX-001", AuditAction.ITEM_ADDED, "Log");
        
        // Act
        List<AuditLog> logs = auditLogService.getAllLogs(100);
        
        // Assert
        assertEquals(2, logs.size());
    }
    
    @Test
    @DisplayName("Should fail getting logs with invalid limit")
    void testGetAllLogsInvalidLimit() {
        // Act & Assert
        assertThrows(IllegalArgumentException.class, () -> {
            auditLogService.getAllLogs(0);
        });
    }
    
    // ========== EXPORT TESTS ==========
    
    @Test
    @DisplayName("Should export logs to CSV format")
    void testExportLogsCSV() {
        // Arrange
        auditLogService.log("LOG-017", "USER-001", "TRX-001", AuditAction.TRANSACTION_START, "Start");
        
        // Act
        boolean result = auditLogService.exportLogs("CSV", "audit_logs.csv");
        
        // Assert
        assertTrue(result);
    }
    
    @Test
    @DisplayName("Should export logs to PDF format")
    void testExportLogsPDF() {
        // Act
        boolean result = auditLogService.exportLogs("PDF", "audit_logs.pdf");
        
        // Assert
        assertTrue(result);
    }
    
    @Test
    @DisplayName("Should export logs to EXCEL format")
    void testExportLogsExcel() {
        // Act
        boolean result = auditLogService.exportLogs("EXCEL", "audit_logs.xlsx");
        
        // Assert
        assertTrue(result);
    }
    
    @Test
    @DisplayName("Should fail exporting with unsupported format")
    void testExportLogsUnsupportedFormat() {
        // Act & Assert
        assertThrows(IllegalArgumentException.class, () -> {
            auditLogService.exportLogs("UNSUPPORTED", "audit_logs.xyz");
        });
    }
    
    @Test
    @DisplayName("Should fail exporting with null format")
    void testExportLogsNullFormat() {
        // Act & Assert
        assertThrows(IllegalArgumentException.class, () -> {
            auditLogService.exportLogs(null, "audit_logs.csv");
        });
    }
    
    @Test
    @DisplayName("Should fail exporting with null filename")
    void testExportLogsNullFilename() {
        // Act & Assert
        assertThrows(IllegalArgumentException.class, () -> {
            auditLogService.exportLogs("CSV", null);
        });
    }
    
    // ========== UTILITY TESTS ==========
    
    @Test
    @DisplayName("Should clear all logs")
    void testClearLogs() {
        // Arrange
        auditLogService.log("LOG-018", "USER-001", "TRX-001", AuditAction.TRANSACTION_START, "Start");
        assertEquals(1, auditLogService.getTotalLogs());
        
        // Act
        auditLogService.clearLogs();
        
        // Assert
        assertEquals(0, auditLogService.getTotalLogs());
    }
}
